import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, GoogleAuthProvider, createUserWithEmailAndPassword, signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { startCloudSync, stopCloudSync, saveCloudProfile } from './cloud-data.js?v=ratings-1';

const firebaseConfig={apiKey:'AIzaSyCgZgwPUo5Ehp5JIdprYfjhIb5VlyJ2RcM',authDomain:'games-loner.firebaseapp.com',projectId:'games-loner',storageBucket:'games-loner.firebasestorage.app',messagingSenderId:'243629336740',appId:'1:243629336740:web:841224ffe9661397781e31'};
const auth=getAuth(getApps()[0]||initializeApp(firebaseConfig));
const provider=new GoogleAuthProvider();
const pageRoot=document.body.dataset.root||(location.pathname.includes('/S%C3%A9ries/')||location.pathname.includes('/Séries/')?'../../':'');
let mode='login';

const modal=document.createElement('div');
modal.className='login-modal';
modal.hidden=true;
modal.innerHTML=`<div class="login-backdrop"></div><section class="login-dialog" role="dialog" aria-modal="true" aria-labelledby="login-modal-title"><button class="login-close" type="button" aria-label="Fechar">×</button><p class="eyebrow">SUA CONTA</p><h2 id="login-modal-title">Entrar no Series Loner</h2><p class="login-intro">Entre para salvar episódios assistidos e ganhar XP.</p><button class="google-login" type="button"><span>G</span>Continuar com Google</button><div class="auth-divider"><span>ou use seu e-mail</span></div><form class="login-form"><label class="username-field" hidden>Nome de usuário<input name="username" type="text" minlength="3" maxlength="24" autocomplete="nickname" placeholder="Escolha seu nome de usuário"></label><label class="email-field">E-mail<input name="email" type="email" autocomplete="email" placeholder="seu@email.com" required></label><label class="password-field">Senha<input name="password" type="password" minlength="6" autocomplete="current-password" placeholder="Mínimo de 6 caracteres" required></label><button class="button button-primary login-submit" type="submit">Entrar</button></form><p class="auth-message" role="status" aria-live="polite"></p><button class="auth-mode" type="button">Não possui conta? Criar conta</button><div class="account-panel" hidden><strong class="account-name"></strong><span class="account-email"></span><a class="button button-primary" href="${pageRoot}perfil.html">Ir Para o Perfil</a><button class="logout-button" type="button">Sair da conta</button></div></section>`;
document.body.appendChild(modal);

const dialog=modal.querySelector('.login-dialog'),form=modal.querySelector('.login-form'),title=modal.querySelector('h2'),intro=modal.querySelector('.login-intro'),message=modal.querySelector('.auth-message'),usernameField=modal.querySelector('.username-field'),emailField=modal.querySelector('.email-field'),passwordField=modal.querySelector('.password-field'),googleButton=modal.querySelector('.google-login'),modeButton=modal.querySelector('.auth-mode'),accountPanel=modal.querySelector('.account-panel');
const profileLogout=document.querySelector('.profile-logout');profileLogout?.addEventListener('click',async()=>{profileLogout.disabled=true;try{await signOut(auth)}finally{profileLogout.disabled=false}});
const usernameKey=user=>{const key=`series-loner-username-${user.uid}`;if(user.displayName&&!localStorage.getItem(key))localStorage.setItem(key,user.displayName);return key};
function showMessage(text,error=false){message.textContent=text;message.classList.toggle('error',error)}
function showHeaderUsername(name){document.querySelectorAll('.header-xp-details>span').forEach(row=>{let label=row.querySelector('.header-user');if(!label){label=document.createElement('strong');label.className='header-user';row.prepend(label)}label.textContent=name})}
function friendly(error){return({'auth/invalid-credential':'E-mail ou senha incorretos.','auth/email-already-in-use':'Este e-mail já possui uma conta.','auth/weak-password':'Use uma senha com pelo menos 6 caracteres.','auth/popup-closed-by-user':'A janela do Google foi fechada.','auth/popup-blocked':'O navegador bloqueou a janela do Google.'})[error.code]||'Não foi possível concluir. Tente novamente.'}
function openModal(nextMode){mode=nextMode||(!window.seriesLonerUser?'login':'account');syncModal();modal.hidden=false;document.body.classList.add('modal-open');setTimeout(()=>dialog.querySelector('input:not([hidden])')?.focus(),30)}
function closeModal(){if(mode==='username')return;modal.hidden=true;document.body.classList.remove('modal-open');showMessage('')}
function syncModal(){const user=window.seriesLonerUser,isRegister=mode==='register',isUsername=mode==='username',isAccount=mode==='account';title.textContent=isRegister?'Criar sua conta':isUsername?'Escolha seu nome de usuário':isAccount?'Sua conta':'Entrar no Series Loner';intro.textContent=isUsername?'Esse nome aparecerá no seu perfil e no ranking.':isAccount?'Sua conta está conectada.':'Entre para salvar episódios assistidos e ganhar XP.';form.hidden=isAccount;accountPanel.hidden=!isAccount;googleButton.hidden=isUsername||isAccount;modal.querySelector('.auth-divider').hidden=isUsername||isAccount;emailField.hidden=isUsername;passwordField.hidden=isUsername;form.email.disabled=isUsername;form.password.disabled=isUsername;usernameField.hidden=!(isRegister||isUsername);usernameField.querySelector('input').required=isRegister||isUsername;form.querySelector('.login-submit').textContent=isRegister?'Criar Conta':isUsername?'Salvar Nome de Usuário':'Entrar';modeButton.hidden=isUsername||isAccount;modeButton.textContent=isRegister?'Já possui conta? Entrar':'Não possui conta? Criar conta';modal.querySelector('.login-close').hidden=isUsername;if(isAccount&&user){modal.querySelector('.account-name').textContent=user.displayName||'Usuário Series Loner';modal.querySelector('.account-email').textContent=user.email||''}}

document.querySelectorAll('.auth-link').forEach(link=>{link.href='#entrar';link.addEventListener('click',event=>{event.preventDefault();openModal()})});
modal.querySelector('.login-close').addEventListener('click',closeModal);modal.querySelector('.login-backdrop').addEventListener('click',closeModal);modeButton.addEventListener('click',()=>openModal(mode==='register'?'login':'register'));modal.querySelector('.logout-button').addEventListener('click',async()=>{await signOut(auth);closeModal()});
form.addEventListener('submit',async event=>{event.preventDefault();showMessage('Aguarde...');const username=form.username.value.trim();try{if(mode==='username'){if(username.length<3)throw{code:'username/short'};await updateProfile(auth.currentUser,{displayName:username});localStorage.setItem(usernameKey(auth.currentUser),username);window.seriesLonerUser=auth.currentUser;showHeaderUsername(username);mode='account';syncModal();showMessage('Nome de usuário salvo.');return}if(mode==='register'){if(username.length<3){showMessage('Escolha um nome com pelo menos 3 caracteres.',true);return}const result=await createUserWithEmailAndPassword(auth,form.email.value.trim(),form.password.value);await updateProfile(result.user,{displayName:username});localStorage.setItem(usernameKey(result.user),username);window.seriesLonerUser=result.user;showHeaderUsername(username);mode='account';syncModal();showMessage('Conta criada com sucesso.')}else await signInWithEmailAndPassword(auth,form.email.value.trim(),form.password.value)}catch(error){showMessage(error.code==='username/short'?'Escolha um nome com pelo menos 3 caracteres.':friendly(error),true)}});
googleButton.addEventListener('click',async()=>{showMessage('Abrindo o Google...');try{await signInWithPopup(auth,provider)}catch(error){showMessage(friendly(error),true)}});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal()});
document.addEventListener('change',event=>{if(event.target.matches('.episode-row input[type="checkbox"]')&&!window.seriesLonerUser){event.preventDefault();event.stopImmediatePropagation();event.target.checked=false;openModal('login')}},true);
document.addEventListener('click',event=>{const button=event.target.closest('.watchlist-button');if(button&&!window.seriesLonerUser){event.preventDefault();event.stopImmediatePropagation();openModal('login')}},true);

const seriesHero=document.querySelector('.series-hero-copy'),seriesSlug=document.body.dataset.page;
const rootPrefix=pageRoot;
const channelPagePath=channel=>`Canais/${String(channel).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('&','-and-').replaceAll('+','-plus-').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}/index.html`;
document.querySelectorAll('.nav-dropdown-menu').forEach(menu=>{if(!menu.querySelector('a[href*="ranking-canais"]')){const link=document.createElement('a');link.href=`${rootPrefix}ranking-canais.html`;link.textContent='Ranking de Canais';menu.appendChild(link)}});
document.querySelectorAll('.site-header nav').forEach(nav=>{if(!nav.querySelector('a[href*="sobre.html"]')){const link=document.createElement('a');link.href=`${rootPrefix}sobre.html`;link.textContent='SOBRE';if(document.body.dataset.page==='about')link.className='active';nav.appendChild(link)}});
if(seriesHero){
  const channelPanel=document.createElement('a');channelPanel.className='series-channel';channelPanel.innerHTML='<span>Canal</span><strong>Carregando...</strong>';
  seriesHero.querySelector('.meta')?.insertAdjacentElement('afterend',channelPanel);
  fetch(`${rootPrefix}series-data.json`).then(response=>response.json()).then(items=>{const title=seriesHero.querySelector('h1')?.textContent.trim(),item=items.find(entry=>entry.title===title||entry.id===seriesSlug),channel=item?.channel||item?.platform||'Não informado';channelPanel.querySelector('strong').textContent=channel;channelPanel.href=`${rootPrefix}${channelPagePath(channel)}`}).catch(()=>channelPanel.querySelector('strong').textContent='Não informado');
}
let ratingPanel=null;
if(seriesHero&&seriesSlug){
  ratingPanel=document.createElement('div');ratingPanel.className='series-rating';ratingPanel.innerHTML='<span class="series-rating-label"><strong data-series-average>Sem avaliações</strong><small>Entre para votar de 1 a 5 estrelas</small></span><span class="rating-stars" role="radiogroup" aria-label="Avaliação da série"></span>';
  const stars=ratingPanel.querySelector('.rating-stars');
  for(let value=1;value<=5;value++){const star=document.createElement('button');star.type='button';star.className='rating-star';star.dataset.value=value;star.setAttribute('role','radio');star.setAttribute('aria-label',`${value} ${value===1?'estrela':'estrelas'}`);star.textContent='★';star.addEventListener('click',()=>{const user=window.seriesLonerUser;if(!user){openModal('login');return}localStorage.setItem(`series-loner-rating-${user.uid}-${seriesSlug}`,String(value));renderSeriesRating(user)});stars.appendChild(star)}
  const watchButton=seriesHero.querySelector('.watchlist-button');seriesHero.insertBefore(ratingPanel,watchButton||null);
}
function renderSeriesRating(user){if(!ratingPanel)return;const value=user?Number(localStorage.getItem(`series-loner-rating-${user.uid}-${seriesSlug}`)||0):0;ratingPanel.querySelectorAll('.rating-star').forEach(star=>{const starValue=Number(star.dataset.value);star.classList.toggle('active',starValue<=value);star.setAttribute('aria-checked',String(starValue===value))});const hint=ratingPanel.querySelector('.series-rating-label small');hint.textContent=user?(value?`Você deu ${value} ${value===1?'estrela':'estrelas'}. Clique para alterar.`:'Escolha de 1 a 5 estrelas'):'Entre para votar de 1 a 5 estrelas'}

function renderSeriesAverage(seriesRatings){if(!ratingPanel)return;const rating=seriesRatings?.[seriesSlug],average=Number(rating?.average)||0,count=Number(rating?.count)||0;ratingPanel.querySelector('[data-series-average]').textContent=count?`★ ${average.toFixed(1)} de 5 · ${count} ${count===1?'avaliação':'avaliações'}`:'Sem avaliações'}
window.addEventListener('seriesloner-ratings-change',event=>renderSeriesAverage(event.detail.seriesRatings));
if(window.seriesLonerRatings)renderSeriesAverage(window.seriesLonerRatings);

window.addEventListener('seriesloner-auth-change',event=>renderSeriesRating(event.detail.user));

if(document.body.dataset.page==='profile'){const panel=document.createElement('section');panel.className='auth-required-panel';panel.innerHTML='<strong>Entre para ver seu perfil</strong><p>Seu nível, XP e séries ficam disponíveis depois do login.</p><button class="button button-primary" type="button">Entrar ou Criar Conta</button>';document.querySelector('.profile-page')?.prepend(panel);panel.querySelector('button').addEventListener('click',()=>openModal('login'))}

onAuthStateChanged(auth,user=>{window.seriesLonerUser=user;document.body.classList.toggle('authenticated',!!user);document.body.classList.add('auth-ready');document.querySelectorAll('.auth-link').forEach(link=>link.textContent='ENTRAR');if(user){const shownName=user.displayName||'Usuário';showHeaderUsername(shownName);const profileTitle=document.querySelector('.profile-head h1');if(profileTitle)profileTitle.textContent=shownName;const avatar=document.querySelector('.avatar>span');if(avatar)avatar.textContent=shownName.charAt(0).toUpperCase();const rankingName=document.querySelector('.current-user .user-name strong');if(rankingName)rankingName.textContent=shownName;const rankingAvatar=document.querySelector('.current-user .rank-avatar');if(rankingAvatar)rankingAvatar.textContent=shownName.charAt(0).toUpperCase()}window.dispatchEvent(new CustomEvent('seriesloner-auth-change',{detail:{user}}));if(user&&!localStorage.getItem(usernameKey(user))){openModal('username')}else if(!modal.hidden){mode=user?'account':'login';syncModal()} });

window.addEventListener('seriesloner-auth-change',event=>{const user=event.detail.user;if(user){startCloudSync(user).catch(error=>console.error('Falha ao iniciar sincronização:',error));if(user.displayName)localStorage.setItem(usernameKey(user),user.displayName)}else stopCloudSync()});
window.addEventListener('seriesloner-cloud-ready',event=>{const key=`series-loner-cloud-ready-${event.detail.user.uid}`;if(!sessionStorage.getItem(key)){sessionStorage.setItem(key,'1');location.reload()}});
window.addEventListener('seriesloner-profile-updated',event=>saveCloudProfile(event.detail.user));
window.SeriesLonerAuth={open:openModal,get user(){return window.seriesLonerUser}};
import('./series-remaining.js?v=1');
