const calendarShows=[];
const calendarCatalogReady=fetch('series-data.json?v=calendar-catalog-2').then(response=>{
  if(!response.ok)throw new Error('catalog');
  return response.json();
}).then(series=>{
  calendarShows.length=0;
  calendarShows.push(...series.filter(item=>Number(item.tvmaze)>0&&item.status!=='Finalizada'&&item.status!=='Cancelada').map(item=>({
    name:item.title,
    slug:item.slug||item.id,
    id:Number(item.tvmaze),
    key:item.storageKey||`series-loner-${item.id}-v1`,
    href:item.page,
    cover:item.image
  })));
}).catch(error=>console.error('Não foi possível carregar o catálogo do calendário.',error));
const today=new Date(),todayKey=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;let calendarDate=new Date(today.getFullYear(),today.getMonth(),1),calendarEvents=[],calendarFilter='all';
function readCalendarState(key){try{return JSON.parse(localStorage.getItem(key))||{}}catch{return{}}}function visibleEvents(){return calendarFilter==='watching'?calendarEvents.filter(event=>readCalendarState(event.key).inWatchlist===true):calendarEvents}function isoDate(date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}function ptDate(value){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`)).replace('.','')}function escapeCalendar(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
async function loadCalendarEvents(){await calendarCatalogReady;try{const response=await fetch('https://api.tvmaze.com/schedule/full');if(!response.ok)throw new Error('schedule');const schedule=await response.json(),byId=new Map(calendarShows.map(show=>[show.id,show]));calendarEvents=schedule.map(episode=>{const show=byId.get(Number(episode._embedded?.show?.id));return show&&episode.airdate&&Number.isInteger(episode.season)&&Number.isInteger(episode.number)?{...show,date:episode.airdate,season:episode.season,episode:episode.number,title:episode.name||'Título a confirmar'}:null}).filter(Boolean).sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name));calendarHighlights.length=0;const seen=new Set();for(const event of calendarEvents.filter(item=>item.date>=todayKey)){if(seen.has(event.slug))continue;seen.add(event.slug);calendarHighlights.push({...event,label:ptDate(event.date).toUpperCase()});if(calendarHighlights.length===10)break}}catch(error){console.error('Não foi possível carregar os lançamentos do calendário.',error);calendarEvents=[]}renderCalendar();renderUpcoming()}
function groupCalendarEvents(events){const groups=new Map();events.forEach(event=>{const group=groups.get(event.slug)||[];group.push(event);groups.set(event.slug,group)});return[...groups.values()].map(group=>group.sort((a,b)=>a.season-b.season||a.episode-b.episode))}
const calendarHighlights=[];
const calendarFilterControls=document.querySelector('.calendar-filters'),calendarHighlightButton=document.createElement('button'),calendarHighlightSection=document.createElement('section');
calendarFilterControls.querySelector('[data-calendar-filter="all"]').textContent='Todas as Séries';calendarFilterControls.querySelector('[data-calendar-filter="watching"]').textContent='Somente as que Assisto';calendarHighlightButton.type='button';calendarHighlightButton.dataset.calendarFilter='highlights';calendarHighlightButton.setAttribute('aria-pressed','false');calendarHighlightButton.textContent='Destaques';calendarFilterControls.appendChild(calendarHighlightButton);calendarHighlightSection.className='calendar-highlights';calendarHighlightSection.hidden=true;document.querySelector('.calendar-intro').insertAdjacentElement('afterend',calendarHighlightSection);
function renderCalendarHighlights(){calendarHighlightSection.innerHTML=`<div class="section-heading"><div><p class="eyebrow">PRÓXIMOS LANÇAMENTOS</p><h2>Destaques do acervo</h2></div></div>${calendarHighlights.length?`<div class="calendar-highlight-grid">${calendarHighlights.map(item=>`<a class="calendar-highlight-card" href="${item.href}"><img src="${item.cover}" alt="Capa de ${escapeCalendar(item.name)}"><div><time>${item.label}</time><h3>${escapeCalendar(item.name)}</h3><span>Ver página da série →</span></div></a>`).join('')}</div>`:'<div class="calendar-empty">Nenhum lançamento futuro confirmado.</div>'}`}
calendarFilterControls.addEventListener('click',event=>{const button=event.target.closest('[data-calendar-filter]');if(!button)return;const highlights=button.dataset.calendarFilter==='highlights';document.querySelector('.calendar-shell').hidden=highlights;document.querySelector('.upcoming-section').hidden=highlights;calendarHighlightSection.hidden=!highlights;if(highlights)renderCalendarHighlights()});
function renderCalendar(){const eventsToShow=visibleEvents(),year=calendarDate.getFullYear(),month=calendarDate.getMonth(),first=new Date(year,month,1),last=new Date(year,month+1,0),start=first.getDay(),total=Math.ceil((start+last.getDate())/7)*7;document.getElementById('calendar-month').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(first);const cells=[];for(let i=0;i<total;i++){const day=i-start+1;if(day<1||day>last.getDate()){cells.push('<div class="calendar-day outside" aria-hidden="true"></div>');continue}const key=isoDate(new Date(year,month,day)),groups=groupCalendarEvents(eventsToShow.filter(event=>event.date===key));cells.push(`<div class="calendar-day ${key===todayKey?'today':''}"><span class="day-number">${day}</span><div class="day-events">${groups.map(group=>{const event=group[0],extra=group.length-1,premiere=group.some(item=>item.season===1&&item.episode===1),watching=readCalendarState(event.key).inWatchlist===true,details=extra?`<span class="calendar-event-details"><b>${escapeCalendar(event.name)}</b>${group.map(item=>`<span><i>T${item.season} E${item.episode}</i>${escapeCalendar(item.title)}</span>`).join('')}</span>`:'';return`<a class="calendar-event ${extra?'has-many':''} ${premiere?'premiere':''} ${watching?'watching':''}" href="${event.href}" aria-label="${escapeCalendar(event.name)} — ${group.length} episódio${group.length===1?'':'s'}"><strong><span>${escapeCalendar(event.name)}</span>${extra?`<b>+${extra}</b>`:''}</strong><small>T${event.season} E${event.episode} · ${escapeCalendar(event.title)}</small>${details}</a>`}).join('')}</div></div>`)}document.getElementById('calendar-grid').innerHTML=cells.join('')}
function renderUpcoming(){const list=document.getElementById('upcoming-list'),future=visibleEvents().filter(event=>event.date>=todayKey),grouped=new Map();future.forEach(event=>{const key=`${event.slug}-${event.date}`,group=grouped.get(key)||[];group.push(event);grouped.set(key,group)});const groups=[...grouped.values()].map(group=>group.sort((a,b)=>a.season-b.season||a.episode-b.episode)).slice(0,12);list.innerHTML=groups.length?groups.map(group=>{const event=group[0],extra=group.length-1,details=extra?`<span class="upcoming-episode-details"><b>${escapeCalendar(event.name)}</b>${group.map(item=>`<span><i>T${item.season} E${item.episode}</i>${escapeCalendar(item.title)}</span>`).join('')}</span>`:'';return`<a class="upcoming-card ${extra?'has-many':''}" href="${event.href}"><img src="${event.cover}" alt="Capa de ${escapeCalendar(event.name)}"><time datetime="${event.date}"><strong>${new Date(`${event.date}T12:00:00`).getDate()}</strong><span>${new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(`${event.date}T12:00:00`)).replace('.','').toUpperCase()}</span></time><div><small>${escapeCalendar(event.name)}${extra?` <b>+${extra}</b>`:''}</small><h3>${escapeCalendar(event.title)}</h3><p>Temporada ${event.season} · Episódio ${event.episode} · ${ptDate(event.date)}</p></div><b>→</b>${details}</a>`}).join(''):`<div class="calendar-empty">${calendarFilter==='watching'?'Nenhum lançamento futuro das séries que você assiste.':'Nenhum lançamento futuro cadastrado.'}</div>`}
document.getElementById('calendar-prev').addEventListener('click',()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar()});document.getElementById('calendar-next').addEventListener('click',()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar()});document.querySelectorAll('[data-calendar-filter]').forEach(button=>button.addEventListener('click',()=>{calendarFilter=button.dataset.calendarFilter;document.querySelectorAll('[data-calendar-filter]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});renderCalendar();renderUpcoming()}));window.addEventListener('storage',()=>{renderCalendar();renderUpcoming()});loadCalendarEvents();
