const calendarShows=[
  {name:'House of the Dragon',slug:'hotd',id:44778,href:'Séries/House of the Dragon/index.html',cover:'Séries/House of the Dragon/Capa.png'},
  {name:'Silo',slug:'silo',id:38052,href:'Séries/Silo/index.html',cover:'Séries/Silo/Capa.png'},
  {name:'Stuart Fails to Save the Universe',slug:'stuart',id:83360,href:'Séries/Stuart Fails to Save the Universe/index.html',cover:'Séries/Stuart Fails to Save the Universe/Capa.png'},
  {name:'The Ark',slug:'ark',id:60153,href:'Séries/The Ark/index.html',cover:'Séries/The Ark/Capa.jpg'}
  ,{name:'Dune: Prophecy',slug:'dune',id:42846,href:'Séries/Dune Prophecy/index.html',cover:'Séries/Dune Prophecy/Capa.png'}
  ,{name:'The Witcher',slug:'witcher',id:28276,href:'Séries/The Witcher/index.html',cover:'Séries/The Witcher/Capa.png'}
];
const today=new Date(),todayKey=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;let calendarDate=new Date(today.getFullYear(),today.getMonth(),1),calendarEvents=[];
function isoDate(date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}function ptDate(value){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`)).replace('.','')}function escapeCalendar(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function calendarFallbacks(){const result=[];const addWeekly=(show,start,count,names={})=>{for(let i=0;i<count;i++){const d=new Date(`${start}T12:00:00`);d.setDate(d.getDate()+i*7);result.push({...show,date:isoDate(d),season:show.season,episode:i+1,title:names[i+1]||'Título a confirmar'})}};addWeekly({...calendarShows[2],season:1},'2026-07-23',10,{1:'Spoiler: Gary Dies'});addWeekly({...calendarShows[3],season:3},'2026-07-29',12,{1:'I Told You Not to Come',2:'The Lucky Ones'});[['2026-08-02',7],['2026-08-09',8]].forEach(([date,episode])=>result.push({...calendarShows[0],date,season:3,episode,title:'Título a confirmar'}));return result}
async function loadCalendarEvents(){const fetched=(await Promise.all(calendarShows.map(async show=>{try{const r=await fetch(`https://api.tvmaze.com/shows/${show.id}/episodes`);if(!r.ok)return[];return(await r.json()).filter(ep=>ep.airdate&&ep.airdate>=todayKey).map(ep=>({...show,date:ep.airdate,season:ep.season,episode:ep.number,title:ep.name||'Título a confirmar'}))}catch{return[]}}))).flat();const merged=new Map();[...calendarFallbacks(),...fetched].filter(e=>e.date>=todayKey).forEach(e=>merged.set(`${e.slug}-${e.season}-${e.episode}`,e));calendarEvents=[...merged.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name));renderCalendar();renderUpcoming()}
function renderCalendar(){const year=calendarDate.getFullYear(),month=calendarDate.getMonth(),first=new Date(year,month,1),last=new Date(year,month+1,0),start=first.getDay(),total=Math.ceil((start+last.getDate())/7)*7;document.getElementById('calendar-month').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(first);const cells=[];for(let i=0;i<total;i++){const day=i-start+1;if(day<1||day>last.getDate()){cells.push('<div class="calendar-day outside" aria-hidden="true"></div>');continue}const key=isoDate(new Date(year,month,day)),events=calendarEvents.filter(e=>e.date===key);cells.push(`<div class="calendar-day ${key===todayKey?'today':''}"><span class="day-number">${day}</span><div class="day-events">${events.map(e=>`<a class="calendar-event ${e.slug}" href="${e.href}" title="${escapeCalendar(e.name)} — ${escapeCalendar(e.title)}"><strong>${escapeCalendar(e.name)}</strong><small>T${e.season} E${e.episode} · ${escapeCalendar(e.title)}</small></a>`).join('')}</div></div>`)}document.getElementById('calendar-grid').innerHTML=cells.join('')}
function renderUpcoming(){const list=document.getElementById('upcoming-list'),events=calendarEvents.slice(0,12);list.innerHTML=events.length?events.map(e=>`<a class="upcoming-card" href="${e.href}"><img src="${e.cover}" alt="Capa de ${escapeCalendar(e.name)}"><time datetime="${e.date}"><strong>${new Date(`${e.date}T12:00:00`).getDate()}</strong><span>${new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(`${e.date}T12:00:00`)).replace('.','').toUpperCase()}</span></time><div><small>${escapeCalendar(e.name)}</small><h3>${escapeCalendar(e.title)}</h3><p>Temporada ${e.season} · Episódio ${e.episode} · ${ptDate(e.date)}</p></div><b>→</b></a>`).join(''):'<div class="calendar-empty">Nenhum lançamento futuro cadastrado.</div>'}
document.getElementById('calendar-prev').addEventListener('click',()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar()});document.getElementById('calendar-next').addEventListener('click',()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar()});loadCalendarEvents();
