const calendarShows=[
  ['Another Life','another-life',36471,'Another Life','series-loner-another-life-v1'],['Lost in Space','lost-in-space',8898,'Lost in Space','series-loner-lost-in-space-v1'],['Scream','scream',1791,'Scream','series-loner-scream-v1'],['Bates Motel','bates-motel',195,'Bates Motel','series-loner-bates-motel-v1'],
  ['American Gods','american-gods',3182,'American Gods','series-loner-progress-v1'],['House of the Dragon','hotd',44778,'House of the Dragon','series-loner-house-dragon-v1'],['The Big Bang Theory','big-bang',66,'The Big Bang Theory','series-loner-big-bang-v1'],['The Acolyte','acolyte',52339,'The Acolyte','series-loner-acolyte-v1'],['Silo','silo',38052,'Silo','series-loner-silo-v1'],['Stuart Fails to Save the Universe','stuart',83360,'Stuart Fails to Save the Universe','series-loner-stuart-v1'],['The Ark','ark',60153,'The Ark','series-loner-the-ark-v1'],
  ['Dune: Prophecy','dune',42846,'Dune Prophecy','series-loner-dune-prophecy-v1'],['Dexter','dexter',161,'Dexter','series-loner-dexter-v1'],['The Walking Dead','walking-dead',73,'The Walking Dead','series-loner-walking-dead-v1'],['The Sandman','sandman',42827,'The Sandman','series-loner-sandman-v1'],['The Witcher','witcher',28276,'The Witcher','series-loner-witcher-v1'],['Stranger Things','stranger-things',2993,'Stranger Things','series-loner-stranger-things-v1'],['Game of Thrones','game-of-thrones',82,'Game of Thrones','series-loner-game-of-thrones-v1'],['Breaking Bad','breaking-bad',169,'Breaking Bad','series-loner-breaking-bad-v1'],['Black Mirror','black-mirror',305,'Black Mirror','series-loner-black-mirror-v1'],['Friends','friends',431,'Friends','series-loner-friends-v1'],['The Last of Us','last-of-us',46562,'The Last of Us','series-loner-last-of-us-v1'],['Dark','dark',17861,'Dark','series-loner-dark-v1'],['WandaVision','wandavision',41748,'WandaVision','series-loner-wandavision-v1'],['Squid Game','squid-game',43687,'Squid Game','series-loner-squid-game-v1'],['Sex Education','sex-education',36795,'Sex Education','series-loner-sex-education-v1'],['Sense8','sense8',1367,'Sense8','series-loner-sense8-v1'],['The Boys','the-boys',15299,'The Boys','series-loner-the-boys-v1'],['Wednesday','wednesday',53647,'Wednesday','series-loner-wednesday-v1'],['How to Get Away with Murder','murder',52,'How to Get Away with Murder','series-loner-how-to-get-away-with-murder-v1'],["That '70s Show",'that-70s-show',587,"That '70s Show",'series-loner-that-70s-show-v1'],['How I Met Your Mother','himym',171,'How I Met Your Mother','series-loner-how-i-met-your-mother-v1'],['How I Met Your Father','himyf',54887,'How I Met Your Father','series-loner-how-i-met-your-father-v1'],['Avatar: The Last Airbender','avatar-last-airbender',38753,'Avatar the Last Airbender','series-loner-avatar-last-airbender-v1'],['Spider-Noir','spider-noir',77003,'Spider-Noir','series-loner-spider-noir-v1'],['A Knight of the Seven Kingdoms','knight-seven-kingdoms',53063,'A Knight of the Seven Kingdoms','series-loner-knight-seven-kingdoms-v1'],["Grey's Anatomy",'greys-anatomy',67,"Grey's Anatomy",'series-loner-greys-anatomy-v1'],['Saving Hope','saving-hope',271,'Saving Hope','series-loner-saving-hope-v1'],['The Good Doctor','the-good-doctor',21845,'The Good Doctor','series-loner-the-good-doctor-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.${folder==='The Ark'?'jpg':'png'}`}));
calendarShows.push(...[['Constantine','constantine',15,'Constantine','series-loner-constantine-v1'],['Gotham','gotham',11,'Gotham','series-loner-gotham-v1'],["Marvel's Daredevil",'marvels-daredevil',1369,"Marvel's Daredevil",'series-loner-marvels-daredevil-v1'],['The Flash','the-flash',13,'The Flash','series-loner-the-flash-v1']].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push({name:'Love Is Blind: France',slug:'love-is-blind-france',id:85871,key:'series-loner-love-is-blind-france-v1',href:'Séries/Love Is Blind France/index.html',cover:'Séries/Love Is Blind France/Capa.png'});
calendarShows.push(...[
  ['Better Call Saul','better-call-saul',618,'Better Call Saul','series-loner-better-call-saul-v1'],['Mr. Robot','mr-robot',1871,'Mr. Robot','series-loner-mr-robot-v1'],["Marvel's Jessica Jones",'marvels-jessica-jones',1370,"Marvel's Jessica Jones",'series-loner-marvels-jessica-jones-v1'],["Marvel's Luke Cage",'marvels-luke-cage',2174,"Marvel's Luke Cage",'series-loner-marvels-luke-cage-v1'],["Marvel's Iron Fist",'marvels-iron-fist',2175,"Marvel's Iron Fist",'series-loner-marvels-iron-fist-v1'],['Ransom Canyon','ransom-canyon',73223,'Ransom Canyon','series-loner-ransom-canyon-v1'],['The Librarians: The Next Chapter','the-librarians-next-chapter',68801,'The Librarians The Next Chapter','series-loner-the-librarians-next-chapter-v1'],['Death Valley','death-valley-2025',84670,'Death Valley','series-loner-death-valley-2025-v1'],['The Fall and Rise of Reggie Dinkins','reggie-dinkins',84605,'The Fall and Rise of Reggie Dinkins','series-loner-reggie-dinkins-v1'],['Widow’s Bay','widows-bay',79390,'Widow’s Bay','series-loner-widows-bay-v1'],['Your Friends and Neighbors','your-friends-neighbors',73484,'Your Friends and Neighbors','series-loner-your-friends-neighbors-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push(...[
  ['Arrow','arrow',4,'Arrow','series-loner-arrow-v1','Capa.png'],["Marvel's Agents of S.H.I.E.L.D.",'marvels-agents-of-shield',31,"Marvel's Agents of S.H.I.E.L.D",'series-loner-marvels-agents-of-shield-v1','Capa.png'],["Marvel's Agent Carter",'marvels-agent-carter',336,"Marvel's Agent Carter",'series-loner-marvels-agent-carter-v1','Capa.png'],['Supergirl','supergirl',1850,'Supergirl','series-loner-supergirl-v1','Capa.png'],["DC's Legends of Tomorrow",'dcs-legends-of-tomorrow',1851,"DC's Legends of Tomorrow",'series-loner-dcs-legends-of-tomorrow-v1','capa.png']
].map(([name,slug,id,folder,key,cover])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/${cover}`})));
calendarShows.push(...[
  ['1670','1670',72655,'1670','series-loner-1670-v1'],['Rain Dogs','rain-dogs',61233,'Rain Dogs','series-loner-rain-dogs-v1'],['Ojitos de Huevo','ojitos-de-huevo',72197,'Ojitos de Huevo','series-loner-ojitos-de-huevo-v1'],['The Power of Parker','the-power-of-parker',63740,'The Power of Parker','series-loner-the-power-of-parker-v1'],['Choona','choona',69840,'Choona','series-loner-choona-v1'],['SisterS','sisters',62458,'SisterS','series-loner-sisters-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push(...[
  ["You're Killing Me",'youre-killing-me',83935,"You're Killing Me",'series-loner-youre-killing-me-v1'],['Lucky','lucky',81228,'Lucky','series-loner-lucky-v1'],['Ted Lasso','ted-lasso',44458,'Ted Lasso','series-loner-ted-lasso-v1'],['Trying','trying',45928,'Trying','series-loner-trying-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push(...[
  ['Sterling Point','sterling-point',82911,'Sterling Point','series-loner-sterling-point-v1'],['Diarra from Detroit','diarra-from-detroit',69170,'Diarra from Detroit','series-loner-diarra-from-detroit-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push({name:'Love Is Blind: Brazil',slug:'love-is-blind-brazil',id:58453,key:'series-loner-love-is-blind-brazil-v1',href:'Séries/Love Is Blind Brazil/index.html',cover:'Séries/Love Is Blind Brazil/Capa.png'});
calendarShows.push(...[
  ['Cape Fear','cape-fear',80946,'Cape Fear','series-loner-cape-fear-v1'],["Let's Marry Harry",'lets-marry-harry',93250,"Let's Marry Harry",'series-loner-lets-marry-harry-v1'],['The Shards','the-shards',68193,'The Shards','series-loner-the-shards-v1'],['The Office','the-office',526,'The Office','series-loner-the-office-v1'],['Seinfeld','seinfeld',530,'Seinfeld','series-loner-seinfeld-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push(...[
  ['My Life with the Walter Boys','my-life-with-the-walter-boys',60523,'My Life with the Walter Boys','series-loner-my-life-with-the-walter-boys-v1'],['Possession','possession',92743,'Possession','series-loner-possession-v1'],['Anna Pigeon','anna-pigeon',84622,'Anna Pigeon','series-loner-anna-pigeon-v1'],['La Casa de Papel','la-casa-de-papel',27436,'La Casa de Papel','series-loner-la-casa-de-papel-v1'],['Lucifer','lucifer',1859,'Lucifer','series-loner-lucifer-v1'],['You','you',26856,'You','series-loner-you-v1'],['Pretty Little Liars','pretty-little-liars',177,'Pretty Little Liars','series-loner-pretty-little-liars-v1'],['Élite','elite',37854,'Elite','series-loner-elite-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push(...[
  ['The Originals','the-originals',62,'The Originals','series-loner-the-originals-v1'],['The Vampire Diaries','the-vampire-diaries',63,'The Vampire Diaries','series-loner-the-vampire-diaries-v1'],['Glee','glee',8,'Glee','series-loner-glee-v1'],['Faking It','faking-it',283,'Faking It','series-loner-faking-it-v1'],['Teen Wolf','teen-wolf',176,'Teen Wolf','series-loner-teen-wolf-v1'],['Once Upon a Time','once-upon-a-time',111,'Once Upon a Time','series-loner-once-upon-a-time-v1'],['Supernatural','supernatural',19,'Supernatural','series-loner-supernatural-v1'],['Brooklyn Nine-Nine','brooklyn-nine-nine',49,'Brooklyn Nine-Nine','series-loner-brooklyn-nine-nine-v1'],['The Good Place','the-good-place',2790,'The Good Place','series-loner-the-good-place-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push(...[
  ['Wizards Beyond Waverly Place','wizards-beyond-waverly-place',77036,'Wizards Beyond Waverly Place','series-loner-wizards-beyond-waverly-place-v1'],['Geek Girl','geek-girl',76501,'Geek Girl','series-loner-geek-girl-v1'],['English Teacher','english-teacher',72758,'English Teacher','series-loner-english-teacher-v1'],['Ted','ted',55832,'Ted','series-loner-ted-v1'],["The Handmaid's Tale",'the-handmaids-tale',16579,"The Handmaid's Tale",'series-loner-the-handmaids-tale-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push(...[
  ['Reacher','reacher',43031,'Reacher','series-loner-reacher-v1'],["Marvel's The Punisher",'marvels-the-punisher',16544,"Marvel's The Punisher",'series-loner-marvels-the-punisher-v1'],['Prison Break','prison-break',541,'Prison Break','series-loner-prison-break-v1'],['Lanterns','lanterns',44776,'Lanterns','series-loner-lanterns-v1'],['The Penguin','the-penguin',60920,'The Penguin','series-loner-the-penguin-v1'],['Dead Boy Detectives','dead-boy-detectives',57400,'Dead Boy Detectives','series-loner-dead-boy-detectives-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push({name:'Lord of the Flies',slug:'lord-of-the-flies',id:68242,key:'series-loner-lord-of-the-flies-v1',href:'Séries/Lord of the Flies/index.html',cover:'Séries/Lord of the Flies/Capa.png'});
calendarShows.push({name:'Fallout',slug:'fallout',id:49041,key:'series-loner-fallout-v1',href:'Séries/Fallout/index.html',cover:'Séries/Fallout/Capa.png'});
calendarShows.push({name:'Harry Potter',slug:'harry-potter',id:0,key:'series-loner-harry-potter-v1',href:'Séries/Harry Potter/index.html',cover:'Séries/Harry Potter/Capa.png'});
calendarShows.push(...[
  ['VisionQuest','visionquest','VisionQuest','series-loner-visionquest-v1'],['Crystal Lake','crystal-lake','Crystal Lake','series-loner-crystal-lake-v1'],['Blade Runner 2099','blade-runner-2099','Blade Runner 2099','series-loner-blade-runner-2099-v1'],['Neuromancer','neuromancer','Neuromancer','series-loner-neuromancer-v1']
].map(([name,slug,folder,key])=>({name,slug,id:0,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push(...[
  ['Star Trek: Strange New Worlds','star-trek-strange-new-worlds',48090,'Star Trek Strange New Worlds','series-loner-star-trek-strange-new-worlds-v1'],['Lioness','lioness',50415,'Lioness','series-loner-lioness-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
calendarShows.push({name:'The Librarians',slug:'the-librarians',id:340,key:'series-loner-the-librarians-v1',href:'Séries/The Librarians/index.html',cover:'Séries/The Librarians/Capa.png'});
calendarShows.push(...[
  ['Las Azules','las-azules',62238,'Las Azules','series-loner-las-azules-v1'],['Me','me',77767,'Me','series-loner-me-v1'],['Baby Bandito','baby-bandito',73413,'Baby Bandito','series-loner-baby-bandito-v1'],['Tracker','tracker',63192,'Tracker','series-loner-tracker-v1']
].map(([name,slug,id,folder,key])=>({name,slug,id,key,href:`Séries/${folder}/index.html`,cover:`Séries/${folder}/Capa.png`})));
const today=new Date(),todayKey=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;let calendarDate=new Date(today.getFullYear(),today.getMonth(),1),calendarEvents=[],calendarFilter='all';
function readCalendarState(key){try{return JSON.parse(localStorage.getItem(key))||{}}catch{return{}}}function visibleEvents(){return calendarFilter==='watching'?calendarEvents.filter(event=>readCalendarState(event.key).inWatchlist===true):calendarEvents}function isoDate(date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}function ptDate(value){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`)).replace('.','')}function escapeCalendar(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function calendarFallbacks(){const result=[];const find=slug=>calendarShows.find(show=>show.slug===slug);const addWeekly=(show,start,count,names={})=>{for(let i=0;i<count;i++){const d=new Date(`${start}T12:00:00`);d.setDate(d.getDate()+i*7);result.push({...show,date:isoDate(d),season:show.season,episode:i+1,title:names[i+1]||'Título a confirmar'})}};addWeekly({...find('stuart'),season:1},'2026-07-23',10,{1:'Spoiler: Gary Dies'});addWeekly({...find('ark'),season:3},'2026-07-29',12,{1:'I Told You Not to Come',2:'The Lucky Ones'});[['2026-08-02',7],['2026-08-09',8]].forEach(([date,episode])=>result.push({...find('hotd'),date,season:3,episode,title:'Título a confirmar'}));for(let episode=1;episode<=8;episode++)result.push({...find('sterling-point'),date:'2026-08-05',season:1,episode,title:`Episódio ${episode}`});[['lanterns','2026-08-16'],['visionquest','2026-10-14'],['crystal-lake','2026-10-15'],['blade-runner-2099','2026-11-25'],['harry-potter','2026-12-25'],['neuromancer','2027-01-22']].forEach(([slug,date])=>result.push({...find(slug),date,season:1,episode:1,title:'Estreia da série'}));return result}
async function fetchEpisodes(show,attempt=0){try{const response=await fetch(`https://api.tvmaze.com/shows/${show.id}/episodes`);if(response.status===429&&attempt<3){await new Promise(resolve=>setTimeout(resolve,1500*(attempt+1)));return fetchEpisodes(show,attempt+1)}if(!response.ok)return[];return(await response.json()).filter(ep=>ep.airdate&&Number.isInteger(ep.season)&&Number.isInteger(ep.number)).map(ep=>({...show,date:ep.airdate,season:ep.season,episode:ep.number,title:ep.name||'Título a confirmar'}))}catch{return[]}}
async function loadCalendarEvents(){const fetched=(await Promise.all(calendarShows.map(fetchEpisodes))).flat();const merged=new Map();[...calendarFallbacks(),...fetched].forEach(event=>merged.set(`${event.slug}-${event.season}-${event.episode}`,event));calendarEvents=[...merged.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name));renderCalendar();renderUpcoming()}
function groupCalendarEvents(events){const groups=new Map();events.forEach(event=>{const group=groups.get(event.slug)||[];group.push(event);groups.set(event.slug,group)});return[...groups.values()].map(group=>group.sort((a,b)=>a.season-b.season||a.episode-b.episode))}
const calendarHighlights=[
  {name:'Lanterns',date:'2026-08-16',label:'16 AGO 2026',folder:'Lanterns'},
  {name:'VisionQuest',date:'2026-10-14',label:'14 OUT 2026',folder:'VisionQuest'},
  {name:'Crystal Lake',date:'2026-10-15',label:'15 OUT 2026',folder:'Crystal Lake'},
  {name:'Blade Runner 2099',date:'2026-11-25',label:'25 NOV 2026',folder:'Blade Runner 2099'},
  {name:'Harry Potter',date:'2026-12-25',label:'25 DEZ 2026',folder:'Harry Potter'},
  {name:'Neuromancer',date:'2027-01-22',label:'22 JAN 2027',folder:'Neuromancer'},
  {name:'Vought Rising',date:'2027-12-31',label:'2027 · DATA A CONFIRMAR',folder:'Vought Rising'},
  {name:'Assassin’s Creed',date:'9999-01-01',label:'DATA A CONFIRMAR',folder:'Assassin’s Creed'},
  {name:'God of War',date:'9999-01-02',label:'DATA A CONFIRMAR',folder:'God of War'},
  {name:'Tomb Raider',date:'9999-01-03',label:'DATA A CONFIRMAR',folder:'Tomb Raider'}
].sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name,'pt-BR'));
const calendarFilterControls=document.querySelector('.calendar-filters'),calendarHighlightButton=document.createElement('button'),calendarHighlightSection=document.createElement('section');
calendarFilterControls.querySelector('[data-calendar-filter="all"]').textContent='Todas as Séries';calendarFilterControls.querySelector('[data-calendar-filter="watching"]').textContent='Somente as que Assisto';calendarHighlightButton.type='button';calendarHighlightButton.dataset.calendarFilter='highlights';calendarHighlightButton.setAttribute('aria-pressed','false');calendarHighlightButton.textContent='Destaques';calendarFilterControls.appendChild(calendarHighlightButton);calendarHighlightSection.className='calendar-highlights';calendarHighlightSection.hidden=true;document.querySelector('.calendar-intro').insertAdjacentElement('afterend',calendarHighlightSection);
function renderCalendarHighlights(){calendarHighlightSection.innerHTML=`<div class="section-heading"><div><p class="eyebrow">ESTREIAS EM DESTAQUE</p><h2>Próximas grandes séries</h2></div></div><div class="calendar-highlight-grid">${calendarHighlights.map(item=>`<a class="calendar-highlight-card" href="Séries/${item.folder}/index.html"><img src="Séries/${item.folder}/Capa.png" alt="Capa de ${escapeCalendar(item.name)}"><div><time>${item.label}</time><h3>${escapeCalendar(item.name)}</h3><span>Ver página da série →</span></div></a>`).join('')}</div>`}
calendarFilterControls.addEventListener('click',event=>{const button=event.target.closest('[data-calendar-filter]');if(!button)return;const highlights=button.dataset.calendarFilter==='highlights';document.querySelector('.calendar-shell').hidden=highlights;document.querySelector('.upcoming-section').hidden=highlights;calendarHighlightSection.hidden=!highlights;if(highlights)renderCalendarHighlights()});
function renderCalendar(){const eventsToShow=visibleEvents(),year=calendarDate.getFullYear(),month=calendarDate.getMonth(),first=new Date(year,month,1),last=new Date(year,month+1,0),start=first.getDay(),total=Math.ceil((start+last.getDate())/7)*7;document.getElementById('calendar-month').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(first);const cells=[];for(let i=0;i<total;i++){const day=i-start+1;if(day<1||day>last.getDate()){cells.push('<div class="calendar-day outside" aria-hidden="true"></div>');continue}const key=isoDate(new Date(year,month,day)),groups=groupCalendarEvents(eventsToShow.filter(event=>event.date===key));cells.push(`<div class="calendar-day ${key===todayKey?'today':''}"><span class="day-number">${day}</span><div class="day-events">${groups.map(group=>{const event=group[0],extra=group.length-1,premiere=group.some(item=>item.season===1&&item.episode===1),watching=readCalendarState(event.key).inWatchlist===true,details=extra?`<span class="calendar-event-details"><b>${escapeCalendar(event.name)}</b>${group.map(item=>`<span><i>T${item.season} E${item.episode}</i>${escapeCalendar(item.title)}</span>`).join('')}</span>`:'';return`<a class="calendar-event ${extra?'has-many':''} ${premiere?'premiere':''} ${watching?'watching':''}" href="${event.href}" aria-label="${escapeCalendar(event.name)} — ${group.length} episódio${group.length===1?'':'s'}"><strong><span>${escapeCalendar(event.name)}</span>${extra?`<b>+${extra}</b>`:''}</strong><small>T${event.season} E${event.episode} · ${escapeCalendar(event.title)}</small>${details}</a>`}).join('')}</div></div>`)}document.getElementById('calendar-grid').innerHTML=cells.join('')}
function renderUpcoming(){const list=document.getElementById('upcoming-list'),future=visibleEvents().filter(event=>event.date>=todayKey),grouped=new Map();future.forEach(event=>{const key=`${event.slug}-${event.date}`,group=grouped.get(key)||[];group.push(event);grouped.set(key,group)});const groups=[...grouped.values()].map(group=>group.sort((a,b)=>a.season-b.season||a.episode-b.episode)).slice(0,12);list.innerHTML=groups.length?groups.map(group=>{const event=group[0],extra=group.length-1,details=extra?`<span class="upcoming-episode-details"><b>${escapeCalendar(event.name)}</b>${group.map(item=>`<span><i>T${item.season} E${item.episode}</i>${escapeCalendar(item.title)}</span>`).join('')}</span>`:'';return`<a class="upcoming-card ${extra?'has-many':''}" href="${event.href}"><img src="${event.cover}" alt="Capa de ${escapeCalendar(event.name)}"><time datetime="${event.date}"><strong>${new Date(`${event.date}T12:00:00`).getDate()}</strong><span>${new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(`${event.date}T12:00:00`)).replace('.','').toUpperCase()}</span></time><div><small>${escapeCalendar(event.name)}${extra?` <b>+${extra}</b>`:''}</small><h3>${escapeCalendar(event.title)}</h3><p>Temporada ${event.season} · Episódio ${event.episode} · ${ptDate(event.date)}</p></div><b>→</b>${details}</a>`}).join(''):`<div class="calendar-empty">${calendarFilter==='watching'?'Nenhum lançamento futuro das séries que você assiste.':'Nenhum lançamento futuro cadastrado.'}</div>`}
document.getElementById('calendar-prev').addEventListener('click',()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);renderCalendar()});document.getElementById('calendar-next').addEventListener('click',()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);renderCalendar()});document.querySelectorAll('[data-calendar-filter]').forEach(button=>button.addEventListener('click',()=>{calendarFilter=button.dataset.calendarFilter;document.querySelectorAll('[data-calendar-filter]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});renderCalendar();renderUpcoming()}));window.addEventListener('storage',()=>{renderCalendar();renderUpcoming()});loadCalendarEvents();
