const selectedChannel=new URLSearchParams(location.search).get('canal')||'';
const channelAliases={'american-gods':'series-loner-progress-v1','hotd':'series-loner-house-dragon-v1','ark':'series-loner-the-ark-v1','dune':'series-loner-dune-prophecy-v1'};
let channelSeries=[],channelScores=null;
const keyForChannelSeries=item=>channelAliases[item.id]||`series-loner-${item.id}-v1`;
const channelEscape=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const channelInitials=value=>value.split(/\s+/).map(word=>word[0]).join('').slice(0,3).toUpperCase();
const localSeriesScore=item=>{try{return JSON.parse(localStorage.getItem(keyForChannelSeries(item))||'{}').inWatchlist?1:0}catch{return 0}};
function renderChannelPage(){const board=document.getElementById('channel-series-board');if(!selectedChannel){document.getElementById('channel-page-title').textContent='Canal não informado';board.innerHTML='<div class="calendar-empty">Escolha um canal no ranking para ver suas séries.</div>';return}document.title=`${selectedChannel} — Séries Loner`;document.getElementById('channel-page-title').textContent=selectedChannel;document.getElementById('channel-breadcrumb').textContent=selectedChannel;document.getElementById('channel-page-mark').textContent=channelInitials(selectedChannel);const ranked=channelSeries.map(item=>({...item,score:channelScores?Number(channelScores[keyForChannelSeries(item)]||0):localSeriesScore(item)})).sort((a,b)=>b.score-a.score||b.rating-a.rating||a.title.localeCompare(b.title,'pt-BR'));const total=ranked.reduce((sum,item)=>sum+item.score,0);document.getElementById('channel-page-summary').textContent=`${ranked.length} ${ranked.length===1?'série cadastrada':'séries cadastradas'} · ${total} ${total===1?'adição nas listas':'adições nas listas'} dos usuários.`;board.innerHTML=ranked.length?ranked.map((item,index)=>`<a class="rank-row channel-series-row ${index===0&&item.score>0?'rank-first':''}" href="${encodeURI(item.page)}"><strong class="rank-position">${String(index+1).padStart(2,'0')}</strong><img src="${encodeURI(item.image)}" alt="Capa de ${channelEscape(item.title)}"><div class="rank-name"><small>${index===0?'MAIS ASSISTIDA':'NO RANKING'}</small><h2>${channelEscape(item.title)}</h2><p>${channelEscape(item.genres.join(' · '))}</p></div><div class="rank-score"><strong>${item.score}</strong><span>${item.score===1?'usuário':'usuários'}</span></div></a>`).join(''):'<div class="calendar-empty">Nenhuma série cadastrada para este canal.</div>'}
window.addEventListener('seriesloner-ranking-change',event=>{channelScores=event.detail.seriesScores;renderChannelPage()});
window.addEventListener('seriesloner-cloud-change',renderChannelPage);
fetch('series-data.json').then(response=>response.json()).then(items=>{channelSeries=items.filter(item=>(item.channel||item.platform)===selectedChannel);renderChannelPage()}).catch(()=>document.getElementById('channel-series-board').innerHTML='<div class="calendar-empty">Não foi possível carregar as séries deste canal.</div>');
