import { getFirestore, doc, getDoc, setDoc, onSnapshot, collection, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';

const firebaseConfig={apiKey:'AIzaSyCgZgwPUo5Ehp5JIdprYfjhIb5VlyJ2RcM',authDomain:'games-loner.firebaseapp.com',projectId:'games-loner',storageBucket:'games-loner.firebasestorage.app',messagingSenderId:'243629336740',appId:'1:243629336740:web:841224ffe9661397781e31'};
const PREFIX='series-loner-',db=getFirestore(getApps()[0]||initializeApp(firebaseConfig)),nativeSet=Storage.prototype.setItem;
const isProgressKey=key=>key.startsWith(PREFIX)&&key.endsWith('-v1');
const safeJson=value=>{try{return JSON.parse(value)}catch{return null}};
let activeUser=null,loading=false,writeTimer=null,unsubscribeUser=null,unsubscribeRanking=null;
function localProgress(){const result={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(isProgressKey(key)){const value=safeJson(localStorage.getItem(key));if(value)result[key]=value}}return result}
function localRatings(uid){const result={},prefix=`${PREFIX}rating-${uid}-`;for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key.startsWith(prefix))result[key.slice(prefix.length)]=Number(localStorage.getItem(key))||0}return result}
function clearProgress(){const keys=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(isProgressKey(key))keys.push(key)}keys.forEach(key=>localStorage.removeItem(key))}
function mergeProgress(local,cloud){const result={...local};Object.entries(cloud||{}).forEach(([key,state])=>{const old=result[key]||{},watched=[...new Set([...(old.watched||[]),...(state.watched||[])])];result[key]={...old,...state,watched,inWatchlist:old.inWatchlist===true||state.inWatchlist===true}});return result}
function totals(progress){return{xp:Object.values(progress||{}).reduce((sum,state)=>sum+(Array.isArray(state?.watched)?state.watched.length:0),0)*22,watchlistCount:Object.values(progress||{}).filter(state=>state?.inWatchlist).length}}
function publishRanking(snapshot){const users=[],seriesScores={};snapshot.forEach(item=>{const data=item.data();users.push({uid:item.id,name:data.name||'Usuário',xp:Number(data.xp)||0});(data.watchlist||[]).forEach(key=>seriesScores[key]=(seriesScores[key]||0)+1)});users.sort((a,b)=>b.xp-a.xp||a.name.localeCompare(b.name));window.dispatchEvent(new CustomEvent('seriesloner-ranking-change',{detail:{users,seriesScores}}))}
async function writeAll(){const progress=localProgress(),stats=totals(progress),name=activeUser.displayName||'Usuário';await Promise.all([setDoc(doc(db,'users',activeUser.uid),{name,progress,ratings:localRatings(activeUser.uid),...stats,updatedAt:serverTimestamp()},{merge:true}),setDoc(doc(db,'publicProfiles',activeUser.uid),{name,xp:stats.xp,watchlist:Object.entries(progress).filter(([,state])=>state?.inWatchlist).map(([key])=>key),updatedAt:serverTimestamp()},{merge:true})])}
function scheduleWrite(){if(!activeUser||loading)return;clearTimeout(writeTimer);writeTimer=setTimeout(()=>writeAll().catch(error=>console.error('Falha ao sincronizar dados:',error)),250)}
Storage.prototype.setItem=function(key,value){nativeSet.call(this,key,value);if(this===localStorage&&(isProgressKey(String(key))||String(key).startsWith(PREFIX+'rating-')))scheduleWrite()};

export async function startCloudSync(user){activeUser=user;loading=true;unsubscribeUser?.();const ref=doc(db,'users',user.uid),snapshot=await getDoc(ref),cloud=snapshot.exists()?snapshot.data():null,owner=localStorage.getItem(`${PREFIX}cloud-owner`),before=localProgress();if(owner){clearProgress();Object.entries(cloud?.progress||{}).forEach(([key,value])=>nativeSet.call(localStorage,key,JSON.stringify(value)))}else{Object.entries(mergeProgress(before,cloud?.progress)).forEach(([key,value])=>nativeSet.call(localStorage,key,JSON.stringify(value)))}nativeSet.call(localStorage,`${PREFIX}cloud-owner`,user.uid);Object.entries(cloud?.ratings||{}).forEach(([slug,value])=>nativeSet.call(localStorage,`${PREFIX}rating-${user.uid}-${slug}`,String(value)));loading=false;await writeAll();unsubscribeUser=onSnapshot(ref,next=>{if(!next.exists()||loading)return;loading=true;const data=next.data();clearProgress();Object.entries(data.progress||{}).forEach(([key,value])=>nativeSet.call(localStorage,key,JSON.stringify(value)));Object.entries(data.ratings||{}).forEach(([slug,value])=>nativeSet.call(localStorage,`${PREFIX}rating-${user.uid}-${slug}`,String(value)));loading=false;window.dispatchEvent(new CustomEvent('seriesloner-cloud-change',{detail:{user,data}}))});window.dispatchEvent(new CustomEvent('seriesloner-cloud-ready',{detail:{user}}))}
export function stopCloudSync(){activeUser=null;clearTimeout(writeTimer);unsubscribeUser?.();unsubscribeUser=null}
export function saveCloudProfile(user){activeUser=user;return writeAll()}
unsubscribeRanking=onSnapshot(collection(db,'publicProfiles'),publishRanking,error=>console.error('Falha ao carregar ranking:',error));
