const channelKeyAliases={
  'american-gods':'series-loner-progress-v1','hotd':'series-loner-house-dragon-v1','ark':'series-loner-the-ark-v1','dune':'series-loner-dune-prophecy-v1'
};
let channelLibrary=[],latestSeriesScores=null,channelRankingPage=0;
const progressKey=item=>channelKeyAliases[item.id]||`series-loner-${item.id}-v1`;
const safeState=key=>{try{return JSON.parse(localStorage.getItem(key))||{}}catch{return{}}};
const initials=name=>name.split(/\s+/).map(word=>word[0]).join('').slice(0,3).toUpperCase();
const channelPage=channel=>`Canais/${String(channel).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('&','-and-').replaceAll('+','-plus-').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}/index.html`;
const escapeChannel=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function localChannelScores(){const scores={};channelLibrary.forEach(item=>{if(safeState(progressKey(item)).inWatchlist){const channel=item.channel||item.platform||'Não informado';scores[channel]=(scores[channel]||0)+1}});return scores}
function aggregateChannelScores(seriesScores){const scores={};channelLibrary.forEach(item=>{const points=Number(seriesScores?.[progressKey(item)]||0);const channel=item.channel||item.platform||'Não informado';scores[channel]=(scores[channel]||0)+points});return scores}
function renderChannelRanking(scores){const board=document.getElementById('channel-ranking-board'),allChannels=[...new Set(channelLibrary.map(item=>item.channel||item.platform||'Não informado'))],rows=allChannels.map(channel=>[channel,Number(scores[channel]||0)]).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'pt-BR')),start=channelRankingPage*50;board.innerHTML=rows.slice(start,start+50).map(([channel,score],offset)=>{const index=start+offset;return`<a class="rank-row channel-rank-row ${index===0&&score>0?'rank-first':''}" href="${channelPage(channel)}"><strong class="rank-position">${String(index+1).padStart(2,'0')}</strong><span class="channel-mark">${escapeChannel(initials(channel))}</span><div class="rank-name"><small>${index===0&&score>0?'CANAL LÍDER':'NO RANKING'}</small><h2>${escapeChannel(channel)}</h2><p>${score} ${score===1?'série adicionada':'séries adicionadas'}</p></div><div class="rank-score"><strong>${score}</strong><span>${score===1?'ponto':'pontos'}</span></div></a>`}).join('');document.querySelector('.channel-ranking-pagination')?.remove();const pages=Math.ceil(rows.length/50);if(pages>1){board.insertAdjacentHTML('afterend',`<nav class="ranking-pagination channel-ranking-pagination" aria-label="Páginas do ranking">${Array.from({length:pages},(_,index)=>`<button type="button" class="${index===channelRankingPage?'active':''}" data-channel-ranking-page="${index}">${index*50+1}–${Math.min((index+1)*50,rows.length)}</button>`).join('')}</nav>`);document.querySelectorAll('[data-channel-ranking-page]').forEach(button=>button.addEventListener('click',()=>{channelRankingPage=Number(button.dataset.channelRankingPage);renderChannelRanking(scores);document.querySelector('.ranking-intro')?.scrollIntoView({behavior:'smooth'})}))}}
window.addEventListener('seriesloner-ranking-change',event=>{latestSeriesScores=event.detail.seriesScores;renderChannelRanking(aggregateChannelScores(latestSeriesScores))});
window.addEventListener('seriesloner-cloud-change',()=>renderChannelRanking(localChannelScores()));
fetch('series-data.json?v=ranking-4').then(response=>response.json()).then(items=>{channelLibrary=items;renderChannelRanking(latestSeriesScores?aggregateChannelScores(latestSeriesScores):localChannelScores())}).catch(()=>document.getElementById('channel-ranking-board').innerHTML='<div class="calendar-empty">Não foi possível carregar os canais.</div>');
